AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'bin/webpack-dev-server'
    - 'bin/webpack'

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/DotPosition:
  EnforcedStyle: trailing
