default: &default
  adapter: postgresql
  hostname: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  reaping_frequency: 10
  encoding: utf-8

development:
  <<: *default
  database: petr_spassky_development

test:
  <<: *default
  database: petr_spassky_test

production:
  <<: *default
  database: petr_spassky_production
